src/compositions/Page/Page.scss
src/compositions/Page/Page.tsx
src/compositions/TopBar/TopBar.scss
src/pages/CollectionPage/CollectionPage.scss
src/pages/CollectionPage/CollectionPage.tsx
src/styles/_index.scss
src/styles/_typography.scss
src/styles/_variables.scss
src/styles/extends/button.scss
src/styles/mixins/index.scss
src/widgets/CollectionWidget/CollectionWidget.scss
src/widgets/CollectionWidget/CollectionWidget.tsx
src/widgets/CollectionWidget/subcomponents/CollectionPortrait/CollectionPortrait.scss
src/widgets/CollectionWidget/subcomponents/CollectionPortrait/CollectionPortrait.tsx
src/widgets/NftDetailWidget/NftDetailWidget.scss
src/widgets/NftDetailWidget/NftDetailWidget.tsx
src/widgets/NftDetailWidget/subcomponents/CollectionPortrait/NftDetailPortrait.scss
src/widgets/NftDetailWidget/subcomponents/CollectionPortrait/NftDetailPortrait.tsx
src/widgets/NftDetailWidget/subcomponents/NftDetailMainInfo/NftDetailMainInfo.scss
src/widgets/NftDetailWidget/subcomponents/NftDetailMainInfo/NftDetailMainInfo.tsx
src/widgets/WalletConnector/WalletConnector.tsx

Fixes #28 
https://user-images.githubusercontent.com/86911296/211207251-0e7587ce-cd69-40f4-a997-5088470664b4.mov
https://user-images.githubusercontent.com/86911296/211207303-643a0897-ecdf-46cd-b34e-6f01dec2906b.mov

28: Added styling for collection and detail portraits

---

craco.config.js
package.json
src/components/WalletInfo/WalletInfo.tsx
src/compositions/MobileMenu/MobileMenu.scss
src/compositions/MobileMenu/MobileMenu.tsx
src/compositions/Page/Page.scss
src/compositions/Page/Page.tsx
src/compositions/TopBar/TopBar.scss
src/compositions/TopBar/TopBar.tsx
src/hooks/useEnsAddress.ts
src/hooks/useToggle.ts
src/index.tsx
src/redux/stores/balances/balancesApi.ts
src/redux/stores/balances/balancesSlice.ts
src/redux/stores/web3/web3Api.ts
src/redux/stores/web3/web3Slice.ts
src/styles/_typography.scss
src/styles/global.scss
src/widgets/WalletConnector/WalletConnector.scss
src/widgets/WalletConnector/WalletConnector.tsx
src/widgets/WalletConnector/subcomponents/WalletProviderList/WalletProviderList.scss
src/widgets/WalletConnector/subcomponents/WalletProviderList/subcomponents/WalletProviderButton/WalletProviderButton.scss

Fixes #27 
- Added mobile and desktop menu for connect wallet buttons
- Added caching for last used provider
- Fixed css duplicate styles bug (removed raco-sass-resources-loader)
https://user-images.githubusercontent.com/86911296/212192670-0f1893fb-f22d-4bd5-a297-4dcbfd2c80ba.mov

27: Connect wallet menu

---

src/components/Avatar/Avatar.tsx
src/components/Button/Button.tsx
src/components/WalletInfo/WalletInfo.scss
src/components/WalletInfo/WalletInfo.tsx
src/compositions/IconButton/IconButton.tsx
src/compositions/MobileMenu/MobileMenu.tsx
src/compositions/Page/Page.tsx
src/compositions/TopBar/TopBar.scss
src/compositions/TopBar/TopBar.tsx
src/compositions/UserPopup/UserPopup.scss
src/compositions/UserPopup/UserPopup.tsx
src/helpers/stringUtils.ts
src/helpers/strings.ts
src/styles/_variables.scss

- fixes #26 
- added user desktop menu component and user icon to `TopBar.tsx`
- adds 'logout' button click functionality
- Avatar is placeholder
- all links direct to `/profile`

Desktop Menu

---

package.json
src/components/ReviewTokenDetails/ReviewTokenDetails.tsx
src/components/TradeDetails/TradeDetails.tsx
src/components/TradeNftDetails/TradeNftDetails.tsx
src/entities/CollectionToken/CollectionTokenTransformers.ts
src/entities/Erc1155Token/Erc1155Token.ts
src/entities/Erc721Token/Erc721Token.ts
src/redux/stores/balances/balancesApi.ts
src/redux/stores/collection/collectionApi.ts
src/redux/stores/metadata/metadataApi.ts
src/redux/stores/metadata/metadataSlice.ts
src/redux/stores/nftDetail/nftDetailApi.ts
yarn.lock

66: Upgrade libraries

---

Procfile
index.js
package.json

Adding requirements for a Heroku instance.

add server (express, index.js), add procfile

---

src/redux/stores/profile/profileApi.ts
src/redux/stores/profile/profileSlice.ts
src/widgets/ProfileWidget/ProfileWidget.scss
src/widgets/ProfileWidget/subcomponents/ConnectedProfileWidget/ConnectedProfileWidget.tsx

Fixes #105 
https://github.com/airswap/airswap-marketplace/assets/86911296/f74cbc23-b920-48f9-8095-2f0929b064de
1. Set REACT_APP_COLLECTION_TOKEN to 0xD000F000Aa1F8accbd5815056Ea32A54777b2Fc4
2. Set REACT_APP_CHAIN_ID to 5
3. Go to a profile page ie http://localhost:3000/#/profile/0x8234B4236bA45003f22E5e2b2aC9296576B085C2/owned-nfts

105: Added pagination to Profile page

---

src/components/WalletInfo/WalletInfo.scss
src/components/WalletInfo/WalletInfo.tsx
src/compositions/MobileMenu/MobileMenu.tsx
src/compositions/Page/Page.tsx
src/compositions/TopBar/TopBar.tsx
src/compositions/UserPopup/UserPopup.tsx
src/pages/ListNftPage/ListNftPage.tsx
src/styles/extends/portrait.scss
src/widgets/CollectionWidget/subcomponents/CollectionPortrait/CollectionPortrait.scss
src/widgets/CollectionWidget/subcomponents/CollectionPortrait/CollectionPortrait.tsx
src/widgets/CollectionWidget/subcomponents/ConnectedCollectionWidget/ConnectedCollectionWidget.tsx
src/widgets/CollectionWidget/subcomponents/DisconnectedCollectionWidget/DisconnectedCollectionWidget.tsx
src/widgets/ListNftWidget/helpers/index.ts
src/widgets/ListNftWidget/subcomponents/DisconnectedListNftWidget/DisconnectedListNftWidget.tsx
src/widgets/ProfileOrdersWidget/ProfileOrdersWidget.tsx
src/widgets/ProfileOrdersWidget/subcomponents/ConnectedProfileOrdersWidget/ConnectedProfileOrdersWidget.tsx
src/widgets/ProfileWidget/ProfileWidget.tsx
src/widgets/ProfileWidget/subcomponents/ConnectedProfileWidget/ConnectedProfileWidget.tsx
src/widgets/ProfileWidget/subcomponents/ProfileHeader/ProfileHeader.tsx
src/widgets/ProfileWidget/subcomponents/ProfileNavigation/ProfileNavigation.tsx
src/widgets/ProfileWidget/subcomponents/ProfileNavigationNavLink/ProfileNavigationNavLink.scss
src/widgets/ProfileWidget/subcomponents/ProfileNavigationNavLink/ProfileNavigationNavLink.tsx

Fixes #124 
Excluding new footer since design is needed.

124: Added textual changes

---

src/compositions/EmptyState/EmptyState.scss
src/compositions/EmptyState/EmptyState.tsx
src/containers/OrdersContainer/OrdersContainer.scss
src/containers/OrdersContainer/OrdersContainer.tsx
src/widgets/CollectionWidget/helpers/getListCallToActionText.ts
src/widgets/CollectionWidget/subcomponents/ConnectedCollectionWidget/ConnectedCollectionWidget.tsx
src/widgets/ProfileOrdersWidget/ProfileOrdersWidget.tsx
src/widgets/ProfileOrdersWidget/helpers/getListCallToActionText.ts
src/widgets/ProfileOrdersWidget/subcomponents/ConnectedProfileOrdersWidget/ConnectedProfileOrdersWidget.tsx
src/widgets/ProfileWidget/ProfileWidget.scss
src/widgets/ProfileWidget/helpers/getEmptyTokensText.ts
src/widgets/ProfileWidget/subcomponents/ConnectedProfileWidget/ConnectedProfileWidget.tsx
src/widgets/ProfileWidget/subcomponents/OwnedNftsContainer/OwnedNftsContainer.scss
src/widgets/ProfileWidget/subcomponents/OwnedNftsContainer/OwnedNftsContainer.tsx

125: Added Empty states

---

src/errors/appError.ts
src/hooks/useIndexedOrderResult.ts
src/redux/stores/indexer/indexerHelpers.ts
src/redux/stores/indexer/indexerHooks.ts
src/redux/stores/indexer/indexerSlice.ts
src/types/IndexedOrderResult.ts
src/widgets/ListNftWidget/helpers/index.ts
src/widgets/ListNftWidget/subcomponents/ConnectedListNftWidget/ConnectedListNftWidget.tsx
src/widgets/ListNftWidget/subcomponents/ListActionButtons/ListActionButtons.tsx
src/widgets/ListNftWidget/subcomponents/ListNftDetailsContainer/ListNftDetailsContainer.tsx

Fixes #126 
After submitting order the order will be sent to indexers. If at least one response is successful within 4 seconds then it is success. Else it fails.
Demonstration of listing fail and success:
https://github.com/airswap/airswap-marketplace/assets/86911296/c7cb42cb-5010-4f3e-9a0a-f4140fdd8994
https://github.com/airswap/airswap-marketplace/assets/86911296/65d639bc-e1ed-408f-a76b-a0a5810bdd35

126: Added error state for failed indexing of order

---

src/redux/stores/nftDetail/nftDetailApi.ts

136: Added fix for not most recent order showing up in detail page

---

src/hooks/useNftTokenOwner.ts
src/widgets/NftDetailWidget/subcomponents/ConnectedNftDetailWidget/ConnectedNftDetailWidget.tsx
src/widgets/NftDetailWidget/subcomponents/NftDetailProceedButton/NftDetailProceedButton.tsx

Fixes #139 
https://github.com/airswap/airswap-marketplace/assets/86911296/1f4eb41c-8b7a-476c-845e-82c394472cdf

139: Added list button to NFT detail page

---

src/compositions/MobileMenu/MobileMenu.tsx
src/compositions/Page/Page.tsx
src/compositions/TopBar/TopBar.tsx
src/widgets/ListNftWidget/subcomponents/ListActionButtons/ListActionButtons.tsx
src/widgets/ProfileWidget/subcomponents/ProfileNavigation/ProfileNavigation.scss
src/widgets/ProfileWidget/subcomponents/ProfileNavigationNavLink/ProfileNavigationNavLink.scss

Fixes #147 
* After listing, clicking a button “view listings” should take to “my listings”
* Remove "Activity" tab on wallet page (until activated)
* Mobile Menu: "My Tokens", "My Listings", "List a Token"

147: Added some textual changes

---

src/redux/stores/collection/collectionApi.ts

153: Added excludeNonces to getCollectionOrders

---

src/entities/FullOrder/FullOrderHelpers.ts

162: Fixed arithmeticUnderflow bug when approving spend erc20

---

package.json
src/components/NftCard/NftCard.scss
src/components/NftCard/NftCard.tsx
src/components/NftCardSkeleton/NftCardSkeleton.scss
src/components/NftCardSkeleton/NftCardSkeleton.tsx
src/containers/OrdersContainer/OrdersContainer.scss
src/containers/OrdersContainer/OrdersContainer.tsx
src/hooks/useCollectionTokens.ts
src/redux/stores/metadata/metadataHooks.ts
src/routes.ts
src/styles/_animations.scss
src/styles/extends/nft.scss
src/widgets/BuyNftWidget/subcomponents/BuyActionButtons/BuyActionButtons.tsx
src/widgets/ListNftWidget/subcomponents/ListActionButtons/ListActionButtons.tsx
src/widgets/ProfileOrdersWidget/subcomponents/ConnectedProfileOrdersWidget/ConnectedProfileOrdersWidget.tsx
src/widgets/ProfileWidget/ProfileWidget.scss
src/widgets/ProfileWidget/subcomponents/ConnectedProfileWidget/ConnectedProfileWidget.tsx
src/widgets/ProfileWidget/subcomponents/DisconnectedProfileWidget/DisconnectedProfileWidget.tsx
src/widgets/ProfileWidget/subcomponents/OwnedNftsContainer/OwnedNftsContainer.scss
src/widgets/ProfileWidget/subcomponents/OwnedNftsContainer/OwnedNftsContainer.tsx
yarn.lock

Fixes #160 
- When nft is listed or bought they will be highlighted when clicking view button.
- @Japlito will take a look at better design for highlight.
https://github.com/airswap/airswap-marketplace/assets/86911296/743e7945-d0bb-4f35-a2c0-1966e1eededa

160: Highlight new order / token

---

src/App.tsx
src/helpers/string.ts
src/hooks/useSwapEventsSubscriber.ts
src/redux/stores/collection/collectionSlice.ts
src/redux/stores/config/configHooks.ts
src/redux/stores/profileOrders/profileOrdersSlice.ts
src/redux/stores/toasts/toastsActions.ts
src/redux/stores/user/userSubscriber.ts
src/widgets/ProfileWidget/subcomponents/ProfileNavigationNavLink/ProfileNavigationNavLink.scss

Fixes #135 
https://github.com/airswap/airswap-marketplace/assets/86911296/07d8397d-5808-47e6-a549-c1ece1a10569

135: Added useSwapEventsSubscriber

---

src/components/NftCard/NftCard.scss
src/components/NftCard/NftCard.tsx
src/containers/OrdersContainer/OrdersContainer.tsx
src/helpers/date/getExpiryTranslation.ts
src/styles/extends/nft.scss
src/widgets/NftDetailWidget/subcomponents/ConnectedNftDetailWidget/ConnectedNftDetailWidget.tsx
src/widgets/NftDetailWidget/subcomponents/NftDetailActivityItem/NftDetailActivityItem.scss
src/widgets/NftDetailWidget/subcomponents/NftDetailSaleInfo/NftDetailSaleInfo.scss
src/widgets/NftDetailWidget/subcomponents/NftDetailSaleInfo/NftDetailSaleInfo.tsx
src/widgets/ProfileOrdersWidget/subcomponents/ConnectedProfileOrdersWidget/ConnectedProfileOrdersWidget.tsx

172: Added expiry to orders page and nft detail page

---

.gitignore
src/widgets/ListNftWidget/ListNftWidget.scss
src/widgets/ListNftWidget/subcomponents/DisconnectedListNftWidget/DisconnectedListNftWidget.tsx
src/widgets/ProfileWidget/subcomponents/ConnectedProfileWidget/ConnectedProfileWidget.tsx

169: Added new empty state for list page

---

src/redux/stores/config/configSlice.ts
src/redux/stores/indexer/indexerApi.ts

Your PR should at least have a ticket number linked to it.
Example:
`Fixes #101`
A short video or an image demonstrating the implementation is also helpful. Especially for designers checking your PR.
Create a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) if you're looking for feedback but not ready for a final review.
Help the reviewer test what you implemented/changed. Include all the steps needed to perform the test.
Example:
1. Add environment variable `REACT_APP_VAR_X=value` in .env file
2. Run `yarn start`
3. Go to home page
4. Click on an NFT
5. Check component XYZ

176 use storage server env variable if set

---

public/index.html

Your PR should at least have a ticket number linked to it.
Example:
`Fixes #101`
A short video or an image demonstrating the implementation is also helpful. Especially for designers checking your PR.
Create a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) if you're looking for feedback but not ready for a final review.
Help the reviewer test what you implemented/changed. Include all the steps needed to perform the test.
Example:
1. Add environment variable `REACT_APP_VAR_X=value` in .env file
2. Run `yarn start`
3. Go to home page
4. Click on an NFT
5. Check component XYZ

178 use ogp image from main website

---

package.json
src/components/ExpiryDateInfo/ExpiryDateInfo.scss
src/components/ExpiryDateInfo/ExpiryDateInfo.tsx
src/components/NftCard/NftCard.tsx
src/containers/ActivityListContainer/subcomponents/NftDetailActivityItem/NftDetailActivityItem.tsx
src/containers/OrdersContainer/subcomponents/OrdersListItem/OrdersListItem.tsx
src/decleration.d.ts
src/redux/stores/balances/balancesApi.ts
src/redux/stores/balances/balancesDeploys.d.ts
src/redux/stores/orders/ordersApi.ts
src/widgets/NftDetailWidget/subcomponents/ConnectedNftDetailWidget/ConnectedNftDetailWidget.tsx
src/widgets/NftDetailWidget/subcomponents/NftDetailMainInfo/NftDetailMainInfo.tsx
src/widgets/NftDetailWidget/subcomponents/NftDetailPortrait/NftDetailPortrait.tsx
src/widgets/ProfileWidget/subcomponents/OwnedNftsContainer/OwnedNftsContainer.tsx
yarn.lock

Added page transition from overview pages to nft detail page. Haven't figured out how to do it the other way but this is a nice start.
Used the new [view transition api](https://developer.chrome.com/docs/web-platform/view-transitions), only works on chrome and edge for now.
https://github.com/airswap/airswap-marketplace/assets/86911296/09911940-6716-4ed9-a978-e1951626c672
https://github.com/airswap/airswap-marketplace/assets/86911296/24bed8e9-0572-4657-9497-29589b4c0262

Added detail page transition animation

---

src/compositions/Page/Page.tsx
src/redux/stores/web3/web3Api.ts
src/redux/stores/web3/web3Slice.ts
src/widgets/WalletConnector/WalletConnector.tsx
yarn.lock

198: Fixed wallet connect modal appearing for a split second on load

---

src/hooks/useCollectionImage.ts
src/redux/stores/metadata/metadataApi.ts
src/redux/stores/metadata/metadataHooks.ts
src/redux/stores/metadata/metadataSlice.ts
src/redux/stores/metadata/metdataHelpers.ts
src/widgets/BuyNftWidget/BuyNftWidget.tsx
src/widgets/BuyNftWidget/subcomponents/ConnectedBuyNftWidget/ConnectedBuyNftWidget.tsx
src/widgets/CancelOrderWidget/subcomponents/ConnectedCancelOrderWidget/ConnectedCancelOrderWidget.tsx
src/widgets/CollectionWidget/subcomponents/ConnectedCollectionWidget/ConnectedCollectionWidget.tsx
src/widgets/CollectionWidget/subcomponents/DisconnectedCollectionWidget/DisconnectedCollectionWidget.tsx
src/widgets/ListNftWidget/subcomponents/ConnectedListNftWidget/ConnectedListNftWidget.tsx
src/widgets/NftDetailWidget/subcomponents/ConnectedNftDetailWidget/ConnectedNftDetailWidget.tsx
src/widgets/ProfileOrdersWidget/subcomponents/ConnectedProfileOrdersWidget/ConnectedProfileOrdersWidget.tsx
src/widgets/ProfileWidget/subcomponents/ConnectedProfileWidget/ConnectedProfileWidget.tsx
src/widgets/ProfileWidget/subcomponents/DisconnectedProfileWidget/DisconnectedProfileWidget.tsx

Fixes #200 
Tried to get banner image by twitter id. But using the twitter api for anything is at least 100 dollars a month. So that's not an option.
So opted for using alchemy that fetches opensea metadata for an address. That includes an optional bannerImage.

200: Added bannerImage to metadata store

---

src/App.tsx
src/compositions/GithubInfo/GithubInfo.scss
src/compositions/GithubInfo/GithubInfo.tsx
src/compositions/UserPopup/UserPopup.scss
src/compositions/UserPopup/UserPopup.tsx
src/redux/stores/filters/filtersHooks.ts
src/redux/stores/listNft/listNftSlice.ts
src/widgets/CollectionWidget/subcomponents/ConnectedCollectionWidget/ConnectedCollectionWidget.tsx
src/widgets/ProfileOrdersWidget/subcomponents/ConnectedProfileOrdersWidget/ConnectedProfileOrdersWidget.tsx

206: Added build version to menu

---

README.md
package.json
src/helpers/enum.ts
src/hooks/useAddressOrEnsName.ts
src/hooks/useEnsAddress.ts
src/redux/stores/config/configHelpers.ts
src/redux/stores/config/configHooks.ts
src/redux/stores/config/configSlice.ts
src/redux/stores/metadata/metdataHelpers.ts
yarn.lock

211: Fixed config debug screen randomly appearing

---

package.json
src/components/NftMedia/NftMedia.scss
src/components/NftMedia/NftMedia.tsx
src/compositions/NftCard/NftCard.scss
src/compositions/NftCard/NftCard.tsx
src/containers/OrdersContainer/subcomponents/OrdersListItem/OrdersListItem.tsx
src/widgets/NftDetailWidget/subcomponents/ConnectedNftDetailWidget/ConnectedNftDetailWidget.tsx
src/widgets/NftDetailWidget/subcomponents/NftDetailPortrait/NftDetailPortrait.scss
src/widgets/NftDetailWidget/subcomponents/NftDetailPortrait/NftDetailPortrait.tsx
src/widgets/ProfileWidget/subcomponents/OwnedNftsContainer/OwnedNftsContainer.tsx
yarn.lock

217: Added video support
